#!/bin/bash

echo -e "************"
echo Compiling...
echo -e "************\n"

mvn compile

echo -e "\n***************************"
echo Copying native libraries...
echo -e "***************************\n"

mvn nativedependencies:copy

##echo -e "\n************"
##echo Packaging...
##echo -e "************\n"

##mvn package

echo Done!
