#!/bin/bash

echo -e "***********"
echo Cleaning...
echo -e "***********\n"

mvn clean:clean

echo -e "\n************"
echo Compiling...
echo -e "************\n"

mvn compile

echo -e "\n***************************"
echo Copying native libraries...
echo -e "***************************\n"

mvn nativedependencies:copy

##echo -e "\n************"
##echo Packaging...
##echo -e "************\n"

##mvn package

echo Done!
