#!/bin/bash

echo -e "******************************"
echo "Installing slick-utils library"
echo -e "*********\n"
mvn install:install-file -Dfile=lib/slick-util.jar -DgroupId=slick-util -DartifactId=slick-util -Dversion=1.0 -Dpackaging=jar

